name: package
on: push

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      pkg_name: redshift-advanced-monitoring.zip
    # required for github oidc
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: install lib
        run: |
          pip install pg8000 -t lib
          pip install pgpasslib -t lib
      - name: setup dist
        run: |
          zip -r $pkg_name lib/
          zip $pkg_name *.py
          zip $pkg_name monitoring-queries.json
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::418861316265:role/github-amazon-redshift-monitoring
          aws-region: us-east-1
      - run: aws s3 cp $pkg_name s3://com.signifyd.redshift/advanced-monitoring/${{github.ref_name}}/
